// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyTrungTam.DAL;

#nullable disable

namespace QuanLyTrungTam.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyTrungTam.Models.BienLaiHocPhi", b =>
                {
                    b.Property<string>("SoBienLai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TienNop")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SoBienLai");

                    b.HasIndex("MaHV");

                    b.HasIndex("MaLop");

                    b.ToTable("BienLaiHocPhi");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.DanhGiaHocVien", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"), 1L, 1);

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("MaHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaHV");

                    b.ToTable("DanhGiaHocVien");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.GiaoVien", b =>
                {
                    b.Property<string>("MaGV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGV");

                    b.ToTable("GiaoVien");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.HocVien", b =>
                {
                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHV");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.KetQuaThi", b =>
                {
                    b.Property<int>("MaKQT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKQT"), 1L, 1);

                    b.Property<decimal>("DiemThi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayThi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoBienLai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XepLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKQT");

                    b.HasIndex("MaHV");

                    b.ToTable("KetQuaThi");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.KhoaHoc", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.LichHoc", b =>
                {
                    b.Property<string>("MaLich")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GioBatDau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioKetThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungBuoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLich");

                    b.HasIndex("MaLop");

                    b.ToTable("LichHoc");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiSo")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaKH");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenDangNhap");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.BienLaiHocPhi", b =>
                {
                    b.HasOne("QuanLyTrungTam.Models.HocVien", "HocVien")
                        .WithMany("BienLaiHocPhis")
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTam.Models.LopHoc", "LopHoc")
                        .WithMany("BienLaiHocPhis")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.DanhGiaHocVien", b =>
                {
                    b.HasOne("QuanLyTrungTam.Models.HocVien", "HocVien")
                        .WithMany("DanhGiaHocViens")
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.KetQuaThi", b =>
                {
                    b.HasOne("QuanLyTrungTam.Models.HocVien", "HocVien")
                        .WithMany("KetQuaThis")
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.LichHoc", b =>
                {
                    b.HasOne("QuanLyTrungTam.Models.LopHoc", "LopHoc")
                        .WithMany("LichHocs")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.LopHoc", b =>
                {
                    b.HasOne("QuanLyTrungTam.Models.GiaoVien", "GiaoVien")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTam.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.GiaoVien", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.HocVien", b =>
                {
                    b.Navigation("BienLaiHocPhis");

                    b.Navigation("DanhGiaHocViens");

                    b.Navigation("KetQuaThis");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.KhoaHoc", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("QuanLyTrungTam.Models.LopHoc", b =>
                {
                    b.Navigation("BienLaiHocPhis");

                    b.Navigation("LichHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
